### ISSUE TITLE
Add ReentrancyGuard in sendEthers function 

### ISSUE THREAD

**Issue by Haripandey21** [malik672/quicknode-bounty#2]
In your contract, sendEthers function is highly vulnerable to Reentracy Attack so add ReentrancyGuard library of Openzeppelin.

## To do that : 
- install openzeppelin in your project by `npm i @openzeppelin/contracts`
- import ReentrancyGuard in our contract by `import "@openzeppelin/contracts/security/ReentrancyGuard.sol";`
- inherit it like this : 
     contract Donate is ReentrancyGuard {........}
- and add nonReentrant modifier in your sendEthers function.

**Comment by malik672** [comment]
will do that
