### ISSUE TITLE
Optimize your smart contract 

### ISSUE THREAD

**Issue by Haripandey21** [malik672/quicknode-bounty#3]
There are some following issues in your contract : 
- Donate.sendEthers(address,uint256)._receiver lacks a zero-check on. 
   Add this :   if(_newAdminAddr!=address(0)){} 
- Donate.addUser(string,uint256) compares to a boolean constant.
   Do this :   require(toCheck, "error"); 
-  Use this Augmented assignment : 
    balance+= amount;
- Change incrementAmounts() function to internal

**Comment by malik672** [comment]
thank you bro, will do that
